import { Inter } from 'next/font/google'
import "../globals.css"
import { useRouter } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

    return (
        <html lang="en">
            <body className={inter.className}>
                <h1 className='text-2xl text-center mb-4'>This is under main layout</h1>
                {children}
            </body>
        </html>
    )
};